version: '3.8'

services:
  fake-job-detector:
    build: .
    container_name: fake_job_detector_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=Fake Job Posting & Recruitment Scam Detector
      - DATABASE_URL=sqlite:///./app.db
      - RISK_THRESHOLD_LOW=30
      - RISK_THRESHOLD_MEDIUM=60
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
